version: 3

dotenv:
  - '.env'

vars:
  DATABASE_URL: postgresql://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSLMODE
  TEST_DATABASE_URL: postgresql://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_TEST_NAME?sslmode=$DB_SSLMODE

tasks:
  create_migration:
      cmds:
        - migrate create -seq -ext=.sql -dir=./internal/db/migrations/ {{ .CLI_ARGS }}

  migrate_up:
      cmds:
        - migrate -path ./internal/db/migrations -database {{ .DATABASE_URL }} -verbose up

  migrate_down:
    cmds:
      - migrate -path ./internal/db/migrations -database {{ .DATABASE_URL }} -verbose down

  test_migrate_up:
    cmds:
      - migrate -path ./internal/db/migrations -database {{ .TEST_DATABASE_URL }} -verbose up

  test_migrate_down:
    cmds:
      - migrate -path ./internal/db/migrations -database {{ .TEST_DATABASE_URL }} -verbose down

  sqlc:
    cmds:
      - sqlc generate

  air:
    cmds:
      - DATABASE_URL={{ .DATABASE_URL }} air