version: 3

dotenv:
  - '.env'

tasks:
  create_migration:
      cmds:
        - migrate create -seq -ext=.sql -dir=./internal/db/migrations/ {{ .CLI_ARGS }}

  migrate_up:
      cmds:
        - migrate -path ./internal/db/migrations -database "postgresql://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSLMODE" -verbose up

  migrate_down:
    cmds:
      - migrate -path ./internal/db/migrations -database "postgresql://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSLMODE" -verbose down