// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HatinIt struct {
	ImageURI  string
	Title     string
	UserID    string
	CreatedAt pgtype.Timestamptz
}

type LovinIt struct {
	Byline     string
	DetailsURI string
	ImageURI   string
	ThumbURI   string
	Title      string
	UserID     string
	LastUsed   pgtype.Date
	CreatedAt  pgtype.Timestamptz
}

type Token struct {
	UserID    string
	Type      string
	ID        string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ID        string
	Admin     bool
}
